; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:esp32doit-devkit-v1]
;platform = espressif32
;board = esp32doit-devkit-v1

;[env:esp-wrover-kit]
;platform = espressif32
;board = esp-wrover-kit

;[env:esp32cam]
;platform = espressif32
;board = esp32cam

[env:ESP32C3_SuperMini] ;works also for ESP32C3_Zero
platform = espressif32
board = esp32-c3-devkitm-1

framework = arduino
upload_protocol = esptool
monitor_speed = 115200

build_flags = 
 ;   -D CORE_DEBUG_LEVEL=3             ;comment out as not working with platformio
	-D ARDUINO_USB_MODE=1             ;use this with ESP32-S3 or ESP32-C3
	-D ARDUINO_USB_CDC_ON_BOOT=1      ;use this with ESP32-S3 or ESP32-C3

lib_deps = 
	esp32async/AsyncTCP@^3.4.9
	esp32async/ESPAsyncWebServer@^3.9.0
	bbx10/DNSServer@^1.1.0
	bblanchon/ArduinoJson@^7.4.2
	yurilopes/SPIFFSIniFile@^1.0.0
	